---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customers-trafficpolicy
spec:
  host: customers.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST

