---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: customers
  namespace: default
spec:
  metadata:
    labels:
      app: customers
  template:
    serviceAccount: customers
